DROP TABLE IF EXISTS raw_insurance_data;
CREATE TABLE raw_insurance_data (
    SEX VARCHAR(255),
    INSR_BEGIN VARCHAR(255),
    INSR_END VARCHAR(255),
    EFFECTIVE_YR VARCHAR(255),
    INSR_TYPE VARCHAR(255),
    INSURED_VALUE VARCHAR(255),
    PREMIUM VARCHAR(255),
    OBJECT_ID VARCHAR(255),
    PROD_YEAR VARCHAR(255),
    SEATS_NUM VARCHAR(255),
    CARRYING_CAPACITY VARCHAR(255),
    TYPE_VEHICLE VARCHAR(255),
    CCM_TON VARCHAR(255),
    MAKE VARCHAR(255),
    USAGE_TYPE VARCHAR(255), 
    CLAIM_PAID VARCHAR(255)
);

USE autoshield_risk_db;
SET GLOBAL local_infile = 1;
LOAD DATA LOCAL INFILE 'C:/Users/ashis/Downloads/motor_data14-2018/motor_data14-2018.csv'
INTO TABLE raw_insurance_data
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;